export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const EXPORT_PLAYLIST = "EXPORT_PLAYLIST";
export const LOAD_PLAYLIST = "LOAD_PLAYLIST";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const SAVE_USER_ID = "SAVE_USER_ID";
export const SAVE_SELECTED_TRACK_ID = "SAVE_SELECTED_TRACK_ID";
export const SAVE_TEMPO = "SAVE_TEMPO";
export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST";
